### ISSUE TITLE
Installation repo in the ReadMe.md is wrong

### ISSUE THREAD

**Issue by anpefi** [adomingues/cleaneRnames#2]
Hi,
thanks for the simple but very useful package. 

I open this issue just to note you about the installation note on the ReadMe.md. You should change the line 
`devtools::install_github("r-lib/usethis")`, that installs Jenny Brian's usethis instead of your package, by
`devtools::install_github("adomingues/cleaneRnames")`

Cheers,
Andrés.

**Comment by adomingues** [comment]
Ah, stupid me copying and pasting without changing links afterwards. Thank you for letting me know @anpefi, it has been corrected now.
